@startuml

class BackupService {
    + BackupJob BackupJob
    
    + AddFile(File file)
}

class BackupJob {
    + JobObject JobObject
    + RestorePoint[] RestorePoints
    + string[] FileNames
}

class RestorePoint {
    + Storage[] Storages
}

class JobObject {
    + string[] FileDestinations
    + string[] FileNames
}

class Storage {
    + string[] FileDestinations
    + string[] FileNames
    
    + void UpLoad()
    + void DownLoad()
}

BackupService o-- BackupJob
BackupJob o-- RestorePoint
BackupJob o-- JobObject
RestorePoint o-- Storage

@enduml