@startuml

class BackupJob {
    + StorageMode StorageMode
    - JobObject JobObject
    - RestorePoint[] RestorePoints
    
    + RestorePoint Archivate(string name)
}

class JobObject {
    + FileInfo[] FileInfos
}

class RestorePoint {
    ~ FileInfo[] LocalFileInfos
    - string Name
    - Storage[] Storages
    
    + void ArchivateSingleMode(string destination, string name)
}

class Storage {
    - File[] FileInfos
}

class FileInfo {
    + string Destination
    + string Name
}

enum StorageMode {
    Single
    Split
}

BackupJob o-- RestorePoint
RestorePoint o-- Storage
Storage o-- FileInfo
BackupJob o-- StorageMode
BackupJob o-- JobObject
JobObject o-- FileInfo

@enduml