@startuml

actor User as UserSender
actor User as UserTaker


package Backup {
    usecase BackupJob
    usecase IJobObject
    usecase RestorePoint  
    usecase IStorage
    usecase FileInfo as FileStorageInfo
    usecase FileInfo as FileJobObjectInfo
}

usecase FileInfo as FileUserInfo
usecase IJobObject as JobObjectUser
usecase ZipArchiver

BackupJob <--> IJobObject
BackupJob --> RestorePoint
RestorePoint <--> IStorage
IStorage <--> FileStorageInfo
IJobObject <--> FileJobObjectInfo

UserSender -> FileUserInfo
FileUserInfo -> JobObjectUser
JobObjectUser -> BackupJob
RestorePoint --> UserTaker
UserTaker --> ZipArchiver

@enduml